name: Build nightly release

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

env:
  UPSTREAM_REPO: yumata/lampa-source

jobs:
  check:
    runs-on: ubuntu-latest

    outputs:
      skip: ${{ steps.check.outputs.skip }}

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Check if build is required
        id: check
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: bash ${{ github.workspace }}/scripts/check.sh

  build:
    runs-on: ubuntu-latest
    needs: check
    if: needs.check.outputs.skip != 'true'
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email \
            "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Clone upstream repo
        run: |
          git clone --depth=1 \
            https://github.com/${{ env.UPSTREAM_REPO }} _source

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 'lts/*'
          package-manager-cache: false

      - name: Install node modules
        working-directory: _source
        run: |
          npm install \
            --no-update-notifier \
            --omit=optional \
            --loglevel=error \
            --no-audit \
            --no-fund

      - name: Install inotify-tools
        run: sudo apt-get install -y --no-install-recommends inotify-tools

      - name: Build web app
        working-directory: _source
        run: bash ${{ github.workspace }}/scripts/build.sh

      - name: Inject settings
        working-directory: _source
        run: bash ${{ github.workspace }}/scripts/settings.sh

      - name: Push to pages branch
        run: bash ${{ github.workspace }}/scripts/pages.sh
